version: '3.7'

services:
  frontend:
    build:
      context: .
      dockerfile: ./Docker/node/Dockerfile
      target: 'develop-stage'
    env_file: .env
    volumes: 
        - .:/app
        - /app/node_modules
    ports:
    - '8080:8080'
    command: /bin/sh -c "yarn run serve"